buildConfiguration:
  buildCommand: npm run build
  installDependenciesStep:
    command: npm install
    requiredFiles:
      - package.json
      - package-lock.json
      - .npmrc
livePreviewConfiguration:
  setupCommand: ":"
siteStream:
  id: site-stream
  entityId: site
  fields:
    - c_visualLayouts.c_visualConfiguration
    - logo
    - c_headerCTAs
    - c_productsAndServicesCmpt
    - c_termsAndConditions
    - c_headquarters.name
    - c_headquarters.address
    - c_headquarters.facebookPageUrl
    - c_headquarters.linkedInUrl
    - c_headquarters.twitterHandle
    - c_headquarters.instagramHandle
    - c_orgId
    - c_themeId
    - c_heroImage
    - c_contactImage
  localization:
    locales:
      - en
